### ISSUE TITLE
Figure out how to measure how many people listen

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/ttw-podcast#2]

**Comment by LucyeoH-zz** [comment]
@adamlofting thinks he can help us get these numbers!  A bunch of people are asking about them so it would be great if we could figure this out.

**Comment by adamlofting** [comment]
There will be a way, but I'll need to do some research. :smile: 

This is now on my todo list.

**Comment by LucyeoH-zz** [comment]
Thanks Adam! :+1:

**Comment by adamlofting** [comment]
Following conversation with @secretrobotron today. some reasonably simple options for this are:
1. Run the RSS feed through feedburner, and use the feedburner version as the RSS feed. This will give stats on reach and subscriber numbers
   - Downsides: Feedburner has been unsupported by Google for a long time and may disappear. You'd have to update the feed URL in itunes.
2.  Run the RSS feeb through [feedblits](http://www.feedblitz.com/)
   - This isn't dead like Feedburner, but it's not clear if the free RSS version actually exists. Slightly difficult site to make sense of. 
3. Rely on S3 logging, but to make this easier, moves the podcast mp3 files into a new bucket that doesn't contain any other files. That way we reduce the complexity for making sense of the logs.

Also, we should add Google Analytics to the promotional site once we have a domain name to link this up with the mentor network site.

**Comment by LucyeoH-zz** [comment]
@secretrobotron any progress on this?

**Comment by secretrobotron** [comment]
@adamlofting showed me a few things that could help. I also ran through the logs we have on S3 and tried to get a feeling for how many people touched the xml and mp3 files. Let me tinker with it some more; the logs are a bit of a mess, but robots are good at reading parseable data and giving us summary information.

**Comment by secretrobotron** [comment]
Preliminary counting results suggest that, as of yesterday, between 300 and 600 people listened to episode 2, and more than 700 listened to episode 1.

In principal, it's easy to download the logs and see how many requests were made, but our load balancer makes the remote IP address field useless (it's always the same). The results above are based on some educated guessing and user-string uniqueness. We can do better though.

**Comment by LucyeoH-zz** [comment]
@secretrobotron what are next steps for implementing a better system? Is it something we can do before we release the next podcast late next week?
