### ISSUE TITLE
March 2015 TTW Talk

### ISSUE THREAD

**Issue by Saallen** [mozilla/ttw-podcast#8]
- [X] Find Speaker
- [x] Define Topic
- [x] Create list of questions for talk
- [x] Come up with catchy name for talk 
- [x] Get speakers Bio
- [x] Make Google Hangout
- [x] Create Discourse page
- [x] Edit BSD email to list serve
- [ ] Send BSD email to list (Monday before the talk) 
- [ ] Start social comms around the talk
- [ ] Final review for talk questions & content 
- [ ] Record TTW Talk
- [ ] Edit Talk for Podcast
- [ ]  Upload to world

**Comment by LucyeoH-zz** [comment]
https://plus.google.com/u/1/events/citnn9u7jljog4gclic6oijdoss
